# 返回函数

## 函数作为返回值

高阶函数除了可以接受函数作为参数外，还可以把函数作为结果值返回。

### 实现一个可变参数的求和

通常情况下，求和的函数是这样定义的：

```python
def calc_sum(*args):
    sum = 0
    for arg in args:
        sum = sum + arg
    return sum

calc_sum(1,2,3,4,5)
# 15
```

如果不需要立刻求和，而是在后面的代码中，根据需要再计算怎么办？

可以不返回求和的结果，而是返回求和的函数：

```python
def lazy_sum(*args):
    def sum():
        sum = 0
        for arg in args:
            sum = sum + arg
        return sum
    return sum

f = lazy_sum(1,2,3,4,5)
f()
# 15
```

我们在函数 `lazy_sum` 中又定义了函数 `sum`，并且，内部函数 `sum` 可以引用外部函数 `lazy_sum` 的参数和局部变量，当 `lazy_sum` 返回函数 `sum` 时，相关参数和变量都保存在返回的函数中，这种称为 **“闭包（Closure）”** 的程序结构拥有极大的威力。

请再注意一点，当我们调用 `lazy_sum()` 时，每次调用都会返回一个新的函数，即使传入相同的参数：

```python
f1 = lazy_sum(1, 3, 5, 7, 9)
f2 = lazy_sum(1, 3, 5, 7, 9)
f1==f2
# False
```

`f1()` 和 `f2()` 的调用结果互不影响。

## 闭包

返回的函数在其定义内部引用了局部变量 `args`，所以，当一个函数返回了一个函数后，其内部的局部变量还被新函数引用。

```python
def count():
    fn_list = []
    for i in range(1, 4):
        def f():
            return i*i
        fn_list.append(f)
    return fn_list

f1, f2, f3 = count()
f1() # 9
f2() # 9
f3() # 9
```

全部都是 `9` 的原因就在于，返回的函数引用了变量 `i`，但它并非立刻执行。

因为等到 `3` 个函数都返回时，它们所引用的变量 `i` 已经变成了 `3`，这时 `f` 函数才被执行，所以返回值为 `9`。

> **返回闭包时**，牢记一点：
>
> 返回函数不要引用任何循环变量，或者后续会发生变化的变量。

如果一定要引用循环变量怎么办？

方法是

1. 再创建一个函数，
2. 用该函数的参数绑定循环变量当前的值，

无论该循环变量后续如何更改，已绑定到函数参数的值不变：

```python
def count():
    fn_list = []
    for i in range(1, 4):
        # highlight-start
        def f(i):
            def g():
                return i*i
            return g
        fn_list.append(f(i)) # f(i)立刻被执行，因此 i 的当前值被传入f()
        # highlight-end
    return fn_list

f1, f2, f3 = count()
f1() # 1
f2() # 4
f3() # 9
```

然后我们再优化一下代码结构：

```python
def count():
    def f(j):
        def g():
            return j*j
        return g
    fs = []
    for i in range(1, 4):
        fs.append(f(i))
    return fs
```

还可以再利用 `lambda` 函数进一步简化代码。

## `nonlocal`

使用闭包，就是内层函数引用了外层函数的局部变量。

如果像上面的 `count` 函数一样，只是读外层变量的值，我们会发现返回的闭包函数调用一切正常：

```python
def inc():
    x = 0
    def fn():
        # 仅读取x的值:
        return x + 1
    return fn

f = inc()
print(f()) # 1
print(f()) # 1
```

但是如果对外层变量赋值，由于 Python 解释器会把在闭包里的局部变量 `x` 当作函数 `fn()` 的局部变量，就会报错。

报错原因是 `x` 作为局部变量并没有初始化，直接计算 `x+1` 是不行的。

所以需要在 `fn()` 函数内部加一个 `nonlocal x` 的声明。

加上这个声明后，解释器把 `fn()` 的 `x` 看作外层函数的局部变量，它已经被初始化了，可以正确计算 `x+1`。

## 练习

利用闭包返回一个计数器函数，每次调用它返回递增整数：

```python
# -*- coding: utf-8 -*-
def createCounter():
    i = 0
    def counter():
        nonlocal i
        i += 1
        return i
    return counter


# 测试:
counterA = createCounter()
print(counterA(), counterA(), counterA(), counterA(), counterA()) # 1 2 3 4 5
counterB = createCounter()
if [counterB(), counterB(), counterB(), counterB()] == [1, 2, 3, 4]:
    print('测试通过!')
else:
    print('测试失败!')
```
